#!/bin/bash
_cryptoo()
{
  local cur prev opts
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  opts="generate_hash verify_hash generate_key_pairs encrypt decrypt enc_des3 dec_des3 sign sign_verify"

  case "${prev}" in

  generate_hash)
    COMPREPLY=( $(compgen -W "--msg --algo" -- ${cur}) )
    return 0
    ;;

  verify_hash)
    COMPREPLY=( $(compgen -W "--msg --digest --algo" -- ${cur}) )
    return 0
    ;;

  encrypt)
    COMPREPLY=( $(compgen -W "--textfile --pubkey" -- ${cur}) )
    return 0
    ;;

  decrypt)
    COMPREPLY=( $(compgen -W "--cipherfile --pvtkey" -- ${cur}) )
    return 0
    ;;

  enc_des3)
    COMPREPLY=( $(compgen -W "--textfile --secret" -- ${cur}) )
    return 0
    ;;

  dec_des3)
    COMPREPLY=( $(compgen -W "--cipherfile --secret" -- ${cur}) )
    return 0
    ;;

  sign)
    COMPREPLY=( $(compgen -W "--textfile --pvtkey" -- ${cur}) )
    return 0
    ;;

  sign_verify)
    COMPREPLY=( $(compgen -W "--textfile --pubkey --signfile" -- ${cur}) )
    return 0
    ;;

  esac

  if [[ $COMP_CWORD -gt 3 ]] ; then

    sec_prev="${COMP_WORDS[COMP_CWORD-2]}"

    thr_prev="${COMP_WORDS[COMP_CWORD-3]}"

      if [[ $thr_prev == generate_hash ]] ; then

        case "${sec_prev}" in
          --msg | -m)
            COMPREPLY=( $(compgen -W "--algo" -- ${cur}) )
            return 0
            ;;
          --algo | -a)
            COMPREPLY=( $(compgen -W "--msg" -- ${cur}) )
            return 0
            ;;
        esac

      fi

      if [[ $thr_prev == verify_hash ]] ; then

        case "${sec_prev}" in
          --msg | -m)
            COMPREPLY=( $(compgen -W "--algo --digest" -- ${cur}) )
            return 0
            ;;
          --algo | -a)
            COMPREPLY=( $(compgen -W "--msg --digest" -- ${cur}) )
            return 0
            ;;
          --digest | -d)
            COMPREPLY=( $(compgen -W "--msg --algo" -- ${cur}) )
            return 0
            ;;
        esac

      fi

      if [[ $thr_prev == encrypt ]] ; then

        case "${sec_prev}" in
          --textfile | -t)
            COMPREPLY=( $(compgen -W "--pubkey" -- ${cur}) )
            return 0
            ;;
          --pubkey | -p)
            COMPREPLY=( $(compgen -W "--textfile" -- ${cur}) )
            return 0
            ;;
        esac

      fi

      if [[ $thr_prev == decrypt ]] ; then

        case "${sec_prev}" in
          --cipherfile | -c)
            COMPREPLY=( $(compgen -W "--pvtkey" -- ${cur}) )
            return 0
            ;;
          --pvtkey | -p)
            COMPREPLY=( $(compgen -W "--cipherfile" -- ${cur}) )
            return 0
            ;;
        esac

      fi

      if [[ $thr_prev == enc_des3 ]] ; then

        case "${sec_prev}" in
          --textfile | -t)
            COMPREPLY=( $(compgen -W "--secret" -- ${cur}) )
            return 0
            ;;
          --secret | -s)
            COMPREPLY=( $(compgen -W "--textfile" -- ${cur}) )
            return 0
            ;;
        esac

      fi

      if [[ $thr_prev == dec_des3 ]] ; then

        case "${sec_prev}" in
          --secret | -s)
            COMPREPLY=( $(compgen -W "--cipherfile" -- ${cur}) )
            return 0
            ;;
          --cipherfile | -c)
            COMPREPLY=( $(compgen -W "--secret" -- ${cur}) )
            return 0
            ;;
        esac

      fi

      if [[ $thr_prev == sign ]] ; then

        case "${sec_prev}" in
          --pvtkey | -p)
            COMPREPLY=( $(compgen -W "--textfile" -- ${cur}) )
            return 0
            ;;
          --textfile | -t)
            COMPREPLY=( $(compgen -W "--pvtkey" -- ${cur}) )
            return 0
            ;;
        esac

      fi

      if [[ $thr_prev == sign_verify ]] ; then

        case "${sec_prev}" in
          --textfile | -t)
            COMPREPLY=( $(compgen -W "--pubkey --signfile" -- ${cur}) )
            return 0
            ;;
          --signfile | -s)
            COMPREPLY=( $(compgen -W "--textfile --pubkey" -- ${cur}) )
            return 0
            ;;
          --pubkey | -p)
            COMPREPLY=( $(compgen -W "--textfile --signfile" -- ${cur}) )
            return 0
            ;;
        esac

      fi

  fi


  if [[ $COMP_CWORD -gt 5 ]] ; then

    sec_prev="${COMP_WORDS[COMP_CWORD-2]}"
    fiv_prev="${COMP_WORDS[COMP_CWORD-5]}"
    for_prev="${COMP_WORDS[COMP_CWORD-4]}"

    if [[ $fiv_prev == verify_hash ]] ; then

      case "${for_prev}" in
        --msg | -m)
          if [[ $sec_prev == --algo ]] ; then
            COMPREPLY=( $(compgen -W "--digest" -- ${cur}) )
          elif [[ $sec_prev == --digest ]] ; then
            COMPREPLY=( $(compgen -W "--algo" -- ${cur}) )
          fi
          return 0
          ;;

        --algo | -a)
          if [[ $sec_prev == --msg ]] ; then
            COMPREPLY=( $(compgen -W "--digest" -- ${cur}) )
          elif [[ $sec_prev == --digest ]] ; then
            COMPREPLY=( $(compgen -W "--msg" -- ${cur}) )
          fi
          return 0
          ;;

        --digest | -d)
          if [[ $sec_prev == --msg ]] ; then
            COMPREPLY=( $(compgen -W "--algo" -- ${cur}) )
          elif [[ $sec_prev == --algo ]] ; then
            COMPREPLY=( $(compgen -W "--msg" -- ${cur}) )
          fi
          return 0
          ;;

      esac

    fi

    if [[ $fiv_prev == sign_verify ]] ; then

      case "${for_prev}" in
        --textfile | -t)
          if [[ $sec_prev == --pubkey ]] ; then
            COMPREPLY=( $(compgen -W "--signfile" -- ${cur}) )
          elif [[ $sec_prev == --signfile ]] ; then
            COMPREPLY=( $(compgen -W "--pubkey" -- ${cur}) )
          fi
          return 0
          ;;

        --pubkey | -p)
          if [[ $sec_prev == --textfile ]] ; then
            COMPREPLY=( $(compgen -W "--signfile" -- ${cur}) )
          elif [[ $sec_prev == --signfile ]] ; then
            COMPREPLY=( $(compgen -W "--textfile" -- ${cur}) )
          fi
          return 0
          ;;

        --signfile | -s)
          if [[ $sec_prev == --textfile ]] ; then
            COMPREPLY=( $(compgen -W "--pubkey" -- ${cur}) )
          elif [[ $sec_prev == --pubkey ]] ; then
            COMPREPLY=( $(compgen -W "--textfile" -- ${cur}) )
          fi
          return 0
          ;;

      esac

    fi

  fi


  if [[ $COMP_CWORD == 1 ]] ; then
    COMPREPLY=($(compgen -W "${opts}" -- ${cur}))
  fi

return 0

}
complete -o default -F _cryptoo cryptoo
